"""initial schema

Revision ID: 5e2b4ddb3fd6
Revises: 
Create Date: 2026-07-23 12:39:20.880926

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e2b4ddb3fd6'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=False),
    sa.Column('source_bill_id', sa.String(), nullable=False),
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('bill_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('sponsors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('status_code', sa.String(), nullable=True),
    sa.Column('last_action_date', sa.Date(), nullable=True),
    sa.Column('introduced_date', sa.Date(), nullable=True),
    sa.Column('full_text_url', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_tax_relevant', sa.Boolean(), nullable=False),
    sa.Column('tax_keywords_matched', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jurisdiction IN ('FEDERAL', 'CA', 'NY')", name='ck_bill_jurisdiction'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jurisdiction', 'source_bill_id', 'session', name='uq_bill_natural_key')
    )
    op.create_index(op.f('ix_bills_jurisdiction'), 'bills', ['jurisdiction'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('bills_seen', sa.Integer(), nullable=False),
    sa.Column('bills_new', sa.Integer(), nullable=False),
    sa.Column('bills_updated', sa.Integer(), nullable=False),
    sa.Column('errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_changes_bill_id'), 'bill_changes', ['bill_id'], unique=False)
    op.create_index(op.f('ix_bill_changes_detected_at'), 'bill_changes', ['detected_at'], unique=False)
    op.create_table('bill_status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('action_text', sa.String(), nullable=False),
    sa.Column('action_code', sa.String(), nullable=True),
    sa.Column('sequence_num', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'event_date', 'action_text', name='uq_status_event')
    )
    op.create_index(op.f('ix_bill_status_events_bill_id'), 'bill_status_events', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_status_events_bill_id'), table_name='bill_status_events')
    op.drop_table('bill_status_events')
    op.drop_index(op.f('ix_bill_changes_detected_at'), table_name='bill_changes')
    op.drop_index(op.f('ix_bill_changes_bill_id'), table_name='bill_changes')
    op.drop_table('bill_changes')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_bills_jurisdiction'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
