"""add relevant_jurisdiction to publications

Revision ID: 768919f9cc79
Revises: b42ba42e6724
Create Date: 2026-08-03 17:03:41.940873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.ingestion.jurisdiction_detect import RELEVANT_JURISDICTIONS

# revision identifiers, used by Alembic.
revision: str = '768919f9cc79'
down_revision: Union[str, Sequence[str], None] = 'b42ba42e6724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('relevant_jurisdiction', sa.String(), nullable=True))
    op.create_index(op.f('ix_publications_relevant_jurisdiction'), 'publications', ['relevant_jurisdiction'], unique=False)
    # ### end Alembic commands ###
    # Alembic's autogenerate doesn't detect new CHECK constraints, so this is added by hand.
    values = ', '.join(repr(j) for j in RELEVANT_JURISDICTIONS)
    op.create_check_constraint(
        'ck_publication_relevant_jurisdiction',
        'publications',
        f'relevant_jurisdiction IS NULL OR relevant_jurisdiction IN ({values})',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_publication_relevant_jurisdiction', 'publications', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_relevant_jurisdiction'), table_name='publications')
    op.drop_column('publications', 'relevant_jurisdiction')
    # ### end Alembic commands ###
