"""add source_label to bills

Revision ID: b3331049055b
Revises: 5e2b4ddb3fd6
Create Date: 2026-07-29 12:20:54.816365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3331049055b'
down_revision: Union[str, Sequence[str], None] = '5e2b4ddb3fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SOURCE_LABELS_BY_JURISDICTION = {
    "FEDERAL": "Congress.gov",
    "CA": "California Legislative Information (PUBINFO)",
    "NY": "NY Senate Open Legislation API",
}


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("bills", sa.Column("source_label", sa.String(), nullable=True))

    bills = sa.table(
        "bills",
        sa.column("jurisdiction", sa.String),
        sa.column("source_label", sa.String),
    )
    for jurisdiction, label in SOURCE_LABELS_BY_JURISDICTION.items():
        op.execute(
            bills.update()
            .where(bills.c.jurisdiction == jurisdiction)
            .values(source_label=label)
        )

    op.alter_column("bills", "source_label", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'source_label')
    # ### end Alembic commands ###
