"""add publications table

Revision ID: b42ba42e6724
Revises: b3331049055b
Create Date: 2026-07-31 11:11:12.263255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b42ba42e6724'
down_revision: Union[str, Sequence[str], None] = 'b3331049055b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_label', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('topic_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('is_tax_relevant', sa.Boolean(), nullable=False),
    sa.Column('tax_keywords_matched', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('PWC_TAX_LIBRARY')", name='ck_publication_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'url', name='uq_publication_natural_key')
    )
    op.create_index(op.f('ix_publications_source'), 'publications', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publications_source'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
